[package]
name = "antler"
version = "2.0.0"
edition = "2024"

[dependencies]
chromatic = "0.0.5"
nalgebra = { version = "0.33.2", features = ["rayon"] }
ndarray = { version = "0.16.1", features = ["rayon"] }
photo = "3.1.1"
rayon = "1.10.0"
