---
name: Badge Generation

on:
    push:
        branches:
            - main

jobs:
    generate-badges:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 2
            - name: Get date
              id: date
              run: echo "##[set-output name=data;]$(date +'%d/%m/%Y')"
            - name: Time badge
              uses: RubbaBoy/BYOB@v1.3.0
              with:
                  NAME: time
                  LABEL: "Released"
                  STATUS: ${{ steps.date.outputs.data }}
                  COLOR: 00c5cd
                  GITHUB_TOKEN: ${{ secrets.BADGE_GENERATION }}
                  PATH: "/antler-time.json"
                  REPOSITORY: FreddyWordingham/_badges_
                  ACTOR: FreddyWordingham
