---
name: Update Documentation

on:
    push:
        branches:
            - main

jobs:
    update_documentation:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os:
                    - ubuntu-latest
                python-version:
                    - 3.8
            fail-fast: false

        steps:
            - name: Checkout sources
              uses: actions/checkout@v2
              with:
                  fetch-depth: 2

            - name: Generate Documentation
              uses: actions-rs/cargo@v1
              with:
                  command: doc

            - name: Push Documentation
              uses: datalbry/copy_folder_to_another_repo_action@1.0.1
              env:
                  API_TOKEN_GITHUB: ${{ secrets.DOCUMENTATION_HOSTING }}
              with:
                  source_folder: "target/doc"
                  destination_repo: "FreddyWordingham/antler"
                  destination_folder: "docs"
                  destination_branch: "docs"
                  user_email: "freddy@digilab.co.uk"
                  user_name: "FreddyWordingham"
                  commit_msg: "Updated documentation"
